### ISSUE TITLE
Its possible?

### ISSUE THREAD

**Issue by krebinha** [ArjixWasTaken/anime-rss#3]
Hey Sorry for my bad english, i from Brazil a start now in python, i have one question, its possible tô get RSS from this site https://geralinks.com.br/ its Dynamics, change every minute, and links redirects to true notíce link, its possible tô make a change in you python code to RSS get this redirect link ?
I like you script. TKS for help.

**Comment by ArjixWasTaken** [comment]
Uhh, it would not make sense to add this to my repository, as it is clearly named anime-rss
nothing about anime is on that site, although i can make a new repo

**Comment by ArjixWasTaken** [comment]
here you go buddy: https://raw.githubusercontent.com/ArjixWasTaken/random-rss-stuff-i-guess/main/geralinks-feed.xml
